---
include:
  - board: xiao_ble//zmk
    shield: dactyl_manuform_4x5_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
  - board: xiao_ble//zmk
    shield: dactyl_manuform_4x5_right -DCONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
